#Prashna Prajapati

#Worksheet-0

#4. TO - DO - Task

#Please complete all the problem listed below.

#4.1 Exercise on Functions:

#Task-1:

Create a Python program that converts between different units of measurement.

• The program should:


1. Prompt the user to choose the type of conversion (e.g., length, weight, volume).

2. Ask the user to input the value to be converted.
3. Perform the conversion and display the result.

4. Handle potential errors, such as invalid input or unsupported conversion types.

• Requirements:

1. Functions: Define at least one function to perform the conversion.

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values).

3. User Input: Prompt the user to select the conversion type and input the value.

4. Docstrings: Include a docstring in your function to describe its purpose, parameters, and return value.

• Conversion Options:

1. Length:

– Convert meters (m) to feet (ft).

– Convert feet (ft) to meters (m).

2. Weight:

– Convert kilograms (kg) to pounds (lbs).

– Convert pounds (lbs) to kilograms (kg).

3. Volume:

– Convert liters (L) to gallons (gal).

– Convert gallons (gal) to liters (L)

In [1]:
def unit_convertor():
  print("Choose conversion type:")
  print("1. Length")
  print("2. Weight")
  print("3. Volume")

  choice = input("Enter 1, 2, or 3: ")

  try:
    value = float(input("Enter value to convert:"))

    if choice == "1":
      print("1. Meters to Feet")
      print("2. Feet to Meters")
      sub = input("Choose option: ")

      if sub == "1":
        result = value * 3.28084
        print("Result:", result, "feet")
        return result

      elif sub == "2":
        result = value / 3.28084
        print("Result:", result, "meters")
        return result

      else:
        print("Invalid length option.")
        return None

    elif choice == "2":
      print("1. Kg to Pounds")
      print("2. Pounds to Kg")
      sub = input("Choose option: ")

      if sub == "1":
          result = value * 2.20462
          print("Result:", result, "lbs")
          return result

      elif sub == "2":
          result = value / 2.20462
          print("Result:", result, "kg")
          return result

      else:
          print("Invalid weight option.")
          return None

    elif choice == "3":
      print("1. Liters to Gallons")
      print("2. Gallons to Liters")
      sub = input("Choose option:")

      if sub == "1":
        result = value * 0.264172
        print("Result:", result, "gallons")
        return result

      elif sub == "2":
        result = value / 0.264172
        print("Result:", result, "liters")
        return result

      else:
        print("Invalid volume option")
        return None

    else:
      print("Invalid main choice.")
      return None

  except ValueError:
    print("Invalid input. Please enter numbers only.")
    return None

unit_convertor()

Choose conversion type:
1. Length
2. Weight
3. Volume
Enter 1, 2, or 3: 3
Enter value to convert:28
1. Liters to Gallons
2. Gallons to Liters
Choose option:2
Result: 105.99155095922353 liters


105.99155095922353

#Task- 2:

Create a Python program that performs various mathematical operations on a list of numbers.

• The Program should:

1. Prompt the user to choose an operation (e.g., find the sum, average, maximum, or minimum of the numbers).

2. Ask the user to input a list of numbers (separated by spaces).

3. Perform the selected operation and display the result.

4. Handle potential errors, such as invalid input or empty lists.

• Requirements:

1. Functions: Define at least one function for each operation (sum, average, maximum, minimum).

2. Error Handling: Use try-except blocks to handle invalid input (e.g., non-numeric values or empty lists).

3. User Input: Prompt the user to select the operation and input the list of numbers.

4. Docstrings: Include a docstring in each function to describe its purpose, parameters, and return value.

In [ ]:
def list_operations():
    numbers_input = input("Enter numbers separated by spaces: ")

    try:
        numbers = [float(num) for num in numbers_input.split()]

        if len(numbers) == 0:
            print("List is empty.")
            return None

        total = sum(numbers)
        average = total / len(numbers)
        maximum = max(numbers)
        minimum = min(numbers)

        print("Sum:", total)
        print("Average:", average)
        print("Maximum:", maximum)
        print("Minimum:", minimum)

        return total, average, maximum, minimum

    except ValueError:
        print("Invalid input. Please enter only numbers.")
        return None

list_operations()

Enter numbers separated by spaces: 3 5 77 8 93
Sum: 186.0
Average: 37.2
Maximum: 93.0
Minimum: 3.0


(186.0, 37.2, 93.0, 3.0)

#4.2 Exercise on List Manipulation:

#1. Extract Every Other Element:

Write a Python function that extracts every other element from a list, starting from the first element.

• Requirements:

– Define a function extract_every_other(lst) that takes a list lst as input and returns a new list containing every other element from the original list.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [1, 3, 5].

In [ ]:
def extract_every_other(lst):
    return lst[::2]

numbers = [1, 2, 3, 4, 5, 6]
result = extract_every_other(numbers)

print("Input:", numbers)
print("Output:", result)

Input: [1, 2, 3, 4, 5, 6]
Output: [1, 3, 5]


#2. Slice a Sublist:

Write a Python function that returns a sublist from a given list, starting from a specified index and ending at another specified index.

• Requirements:

– Define a function get_sublist(lst, start, end) that takes a list lst, a starting index start, and an ending index end as input and returns the sublist from start to end (inclusive).

– Example: For the input [1, 2, 3, 4, 5, 6] with start=2 and end=4, the output should be [3, 4, 5].

In [ ]:
def get_sublist(lst, start, end):
    return lst[start:end+1]

numbers = [1, 2, 3, 4, 5, 6]
sublist = get_sublist(numbers, 2, 4)

print("Input:", numbers)
print("Sublist from index 2 to 4:", sublist)

Input: [1, 2, 3, 4, 5, 6]
Sublist from index 2 to 4: [3, 4, 5]


#3. Reverse a List Using Slicing:

Write a Python function that reverses a list using slicing.

• Requirements:

– Define a function reverse_list(lst) that takes a list lst and returns a reversed list using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [5, 4, 3, 2, 1].


In [ ]:
def reverse_list(lst):
    return lst[::-1]

numbers = [1, 2, 3, 4, 5]
reversed_numbers = reverse_list(numbers)

print("Input:", numbers)
print("Reversed:", reversed_numbers)

Input: [1, 2, 3, 4, 5]
Reversed: [5, 4, 3, 2, 1]


#4. Remove the First and Last Elements:

Write a Python function that removes the first and last elements of a list and returns the resulting sublist.

• Requirements:

– Define a function remove_first_last(lst) that takes a list lst and returns a sublist without the first and last elements using slicing.

– Example: For the input [1, 2, 3, 4, 5], the output should be [2, 3, 4].

In [ ]:
def remove_first_last(lst):
    return lst[1:-1]

numbers = [1, 2, 3, 4, 5]
result = remove_first_last(numbers)

print("Input:", numbers)
print("After removing first and last elements:", result)

Input: [1, 2, 3, 4, 5]
After removing first and last elements: [2, 3, 4]


#5. Get the First n Elements:

Write a Python function that extracts the first n elements from a list.

• Requirements:

– Define a function get_first_n(lst, n) that takes a list lst and an integer n as input and returns the first n elements of the list using slicing.

– Example: For the input [1, 2, 3, 4, 5] with n=3, the output should be [1, 2, 3].

In [ ]:
def get_first_n(lst, n):
    return lst[:n]

numbers = [1, 2, 3, 4, 5]
result = get_first_n(numbers, 3)

print("Input:", numbers)
print("First 3 elements:", result)

Input: [1, 2, 3, 4, 5]
First 3 elements: [1, 2, 3]


#6. Extract Elements from the End:

Write a Python function that extracts the last n elements of a list using slicing.

• Requirements:

– Define a function get_last_n(lst, n) that takes a list lst and an integer n as input and returns the last n elements of the list.

– Example: For the input [1, 2, 3, 4, 5] with n=2, the output should be [4, 5].

In [ ]:
def get_last_n(lst, n):
  return lst[-n:]

numbers = [1, 2, 3, 4, 5]
result = get_last_n(numbers, 2)

print("Input:", numbers)
print("Last 2 elements:", result)

Input: [1, 2, 3, 4, 5]
Last 2 elements: [4, 5]


#7. Extract Elements in Reverse Order:

Write a Python function that extracts a list of elements in reverse order starting from the second-to-last
element and skipping one element in between.

• Requirements:

– Define a function reverse_skip(lst) that takes a list lst and returns a new list containing every second element starting from the second-to-last, moving backward.

– Example: For the input [1, 2, 3, 4, 5, 6], the output should be [5, 3, 1].

In [ ]:
def reverse_skip(lst):
  return lst[-2::-2]

numbers = [1, 2, 3, 4, 5, 6]
result = reverse_skip(numbers)

print("Input:", numbers)
print("Output (every second element starting from the second-to-last):", result)

Input: [1, 2, 3, 4, 5, 6]
Output (every second element starting from the second-to-last): [5, 3, 1]


#4.3 Exercise on Nested List:

#1. Flatten a Nested List:

Write a Python function that takes a nested list and flattens it into a single list, where all the elements are in a single dimension.

• Requirements:

– Define a function flatten(lst) that takes a nested list lst and returns a flattened version of the list.

– Example: For the input [[1, 2], [3, 4], [5]], the output should be [1, 2, 3, 4, 5].

In [ ]:
def flatten(lst):
  return [item for sublist in lst for item in sublist]

nested_list = [[1, 2], [3, 4], [5]]
result = flatten(nested_list)

print("Input:", nested_list)
print("Flattened list:", result)

Input: [[1, 2], [3, 4], [5]]
Flattened list: [1, 2, 3, 4, 5]


#2. Accessing Nested List Elements:

Write a Python function that extracts a specific element from a nested list given its indices.

• Requirements:

– Define a function access_nested_element(lst, indices) that takes a nested list lst and a list of indices indices, and returns the element at that position.

– Example: For the input lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]] with indices = [1,2], the output should be 6.

In [ ]:
def access_nested_element(lst, indices):
  element = lst
  for index in indices:
    element = element[index]
  return element

nested_list = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
indices = [1, 2]
result = access_nested_element(nested_list, indices)

print("Input nested list:", nested_list)
print("Indices:", indices)
print("Extracted element:", result)

Input nested list: [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Indices: [1, 2]
Extracted element: 6


#3. Sum of All Elements in a Nested List:

Write a Python function that calculates the sum of all the numbers in a nested list (regardless of depth).

• Requirements:

– Define a function sum_nested(lst) that takes a nested list lst and returns the sum of all the elements.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 21.

In [ ]:
def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, type([])):
            total += sum_nested(item)
        else:
            total += item
    return total

nested_list = [[1, 2], [3, [4, 5]], 6]
sum_result = sum_nested(nested_list)

print("Input nested list:", nested_list)
print("Sum of all elements:", sum_result)

Input nested list: [[1, 2], [3, [4, 5]], 6]
Sum of all elements: 21


#4. Remove Specific Element from a Nested List:

Write a Python function that removes all occurrences of a specific element from a nested list.

• Requirements:

– Define a function remove_element(lst, elem) that removes elem from lst and returns the modified list.

– Example: For the input lst = [[1, 2], [3, 2], [4, 5]]andelem = 2,the output should be [[1], [3], [4, 5]].

In [ ]:
def remove_element(lst, elem):
    new_list = []
    for item in lst:
        if isinstance(item, type([])):
            new_sublist = remove_element(item, elem)
            new_list.append(new_sublist)
        else:
            if item != elem:
                new_list.append(item)
    return new_list

nested_list = [[1, 2], [3, 2], [4, 5]]
elem_to_remove = 2

result = remove_element(nested_list, elem_to_remove)

print("Input nested list:", nested_list)
print(f"After removing {elem_to_remove}:", result)

Input nested list: [[1, 2], [3, 2], [4, 5]]
After removing 2: [[1], [3], [4, 5]]


#5. Find the Maximum Element in a Nested List:

Write a Python function that finds the maximum element in a nested list (regardless of depth).

• Requirements:

– Define a function find_max(lst) that takes a nested list lst and returns the maximum elememt.

– Example: For the input [[1, 2], [3, [4, 5]], 6], the output should be 6.

In [ ]:
def find_max(lst):
    max_val = float('-inf')
    for item in lst:
        if isinstance(item, type([])):
            max_val = max(max_val, find_max(item))
        else:
            max_val = max(max_val, item)
    return max_val

nested_list = [[1, 2], [3, [4, 5]], 6]
max_element = find_max(nested_list)

print("Input nested list:", nested_list)
print("Maximum element:", max_element)

Input nested list: [[1, 2], [3, [4, 5]], 6]
Maximum element: 6


#6. Count Occurrences of an Element in a Nested List:

Write a Python function that counts how many times a specific element appears in a nested list.

• Requirements:

– Define a function count_occurrences(lst, elem) that counts the occurrences of elem in the nested list lst.

– Example: For the input lst = [[1, 2], [2, 3], [2, 4]] and elem = 2,the output should be 3.

In [ ]:
def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, type([])):
            count += count_occurrences(item, elem)
        else:
          if item == elem:
            count += 1
    return count

nested_list = [[1, 2], [2, 3], [2, 4]]
element_to_count = 2
result = count_occurrences(nested_list, element_to_count)

print("Input nested list:", nested_list)
print(f"Occurrences of {element_to_count}:", result)

Input nested list: [[1, 2], [2, 3], [2, 4]]
Occurrences of 2: 3


#7. Flatten a List of Lists of Lists:

Write a Python function that flattens a list of lists of lists into a single list, regardless of the depth.

• Requirements:

– Define a function deep_flatten(lst) that takes a deeply nested list lst and returns a single flattened list.

– Example: For the input [[[1, 2], [3, 4]], [[5, 6], [7, 8]]], the output should be [1, 2, 3, 4, 5, 6, 7, 8].

In [ ]:
def deep_flatten(lst):
  flat_list = []
  for item in lst:
    if isinstance(item, type([])):
      flat_list.extend(deep_flatten(item))
    else:
      flat_list.append(item)
  return flat_list

nested_list = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
result = deep_flatten(nested_list)

print("Input nested list:", nested_list)
print("Flattened list:", result)

Input nested list: [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8]


#8. Nested List Average:

Write a Python function that calculates the average of all elements in a nested list.

• Requirements:

– Define a function average_nested(lst) that takes a nested list lst and returns the average of all the elements.

– Example: For the input [[1, 2], [3, 4], [5, 6]], the output should be 3.5.

In [ ]:
def average_nested(lst):
    def sum_and_count(sublist):
        total_sum = 0
        total_count = 0
        for item in sublist:
            if isinstance(item, type([])):
                s, c = sum_and_count(item)
                total_sum += s
                total_count += c
            else:
                total_sum += item
                total_count += 1
        return total_sum, total_count

    total_sum, total_count = sum_and_count(lst)
    return total_sum / total_count if total_count > 0 else 0

nested_list = [[1, 2], [3, 4], [5, 6]]
result = average_nested(nested_list)

print("Input nested list:", nested_list)
print("Average of all elements:", result)

Input nested list: [[1, 2], [3, 4], [5, 6]]
Average of all elements: 3.5


#10 To- Do- NumPy

#Please complete all the problems listed below:

#10.1 Basic Vector and Matrix Operation with Numpy.

#Problem- 1: Array Creation:

Complete the following Tasks:
1. Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

empty_array = np.empty((2, 2))

print("Empty 2x2 array:")
print(empty_array)

Empty 2x2 array:
[[0. 0.]
 [0. 0.]]


2. Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

ones_array = np.ones((4, 2))

print("All-one 4x2 array:")
print(ones_array)

All-one 4x2 array:
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

filled_array = np.full((3, 3), 7)

print("Filled 3x3 array with 7:")
print(filled_array)


Filled 3x3 array with 7:
[[7 7 7]
 [7 7 7]
 [7 7 7]]


4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros_like}

In [ ]:
import numpy as np

original_array = np.array([[1, 2, 3], [4, 5, 6]])

zeros_array = np.zeros_like(original_array)

print("Original array:")
print(original_array)
print("\nZeros array with same shape and type:")
print(zeros_array)

Original array:
[[1 2 3]
 [4 5 6]]

Zeros array with same shape and type:
[[0 0 0]
 [0 0 0]]


5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones_like}

In [ ]:
import numpy as np

original_array = np.array([[10, 20, 30], [40, 50, 60]])

ones_array = np.ones_like(original_array)

print("Original array:")
print(original_array)
print("\nOnes array with same shape and type:")
print(ones_array)

Original array:
[[10 20 30]
 [40 50 60]]

Ones array with same shape and type:
[[1 1 1]
 [1 1 1]]


6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]

numpy_array = np.array(new_list)

print("Numpy Array:")
print(numpy_array)

Numpy Array:
[1 2 3 4]


#Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:

Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array = np.arange(10, 50)

print("Array with values ranging from 10 to 49:")
print(array)

Array with values ranging from 10 to 49:
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

array = np.arange(9)

matrix = array.reshape(3, 3)

print("3x3 Matrix with values ranging from 0 to 8:")
print(matrix)

3x3 Matrix with values ranging from 0 to 8:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

identity_matrix = np.eye(3)

print("3x3 Identity Matrix:")
print(identity_matrix)

3x3 Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

random_array = np.random.random(30)

mean_value = random_array.mean()

print("Random Array:")
print(random_array)
print("\nMean of the Array:")
print(mean_value)

Random Array:
[0.80854121 0.38108521 0.70444618 0.49813698 0.32789672 0.47407275
 0.70187215 0.54560019 0.19356574 0.66855908 0.75430048 0.96600028
 0.09850065 0.4358341  0.3655879  0.06754558 0.22749709 0.02866935
 0.6531582  0.8424921  0.32987472 0.34231938 0.43390739 0.16416636
 0.84572876 0.22324617 0.11250786 0.5251857  0.52153898 0.72562041]

Mean of the Array:
0.465581921901475


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

random_array = np.random.random((10, 10))

min_value = random_array.min()
max_value = random_array.max()

print("Random 10x10 Array:")
print(random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array:
[[0.26122278 0.58702822 0.38509198 0.70156631 0.46894564 0.91781797
  0.63281275 0.22532606 0.61688289 0.60992824]
 [0.67481584 0.07661144 0.6893209  0.72963655 0.2364608  0.22407699
  0.2680521  0.8980162  0.76444834 0.84420667]
 [0.44816915 0.11979306 0.13612477 0.34065237 0.47194158 0.74830579
  0.93702569 0.25451725 0.77576154 0.46836206]
 [0.08815222 0.5648063  0.49984105 0.74850602 0.28209128 0.80799913
  0.74463456 0.21327446 0.14867863 0.69758377]
 [0.24103944 0.62157431 0.95670761 0.10518024 0.38846311 0.71460542
  0.85050345 0.3183749  0.27317254 0.10149726]
 [0.20684392 0.83244546 0.72425795 0.56667887 0.22954766 0.32925352
  0.39264331 0.70504759 0.9320674  0.78726349]
 [0.25932331 0.03095882 0.90208819 0.42606725 0.95002683 0.44423054
  0.91920337 0.81857075 0.71508669 0.9743422 ]
 [0.19436776 0.56960782 0.51350528 0.65843125 0.38086114 0.99503432
  0.10147794 0.30333536 0.18829396 0.70324897]
 [0.42749992 0.06215842 0.26865622 0.16021352 0.04213559 0.0

6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

zero_array = np.zeros(10)

zero_array[4] = 1

print("Zero Array with 5th Element Replaced:")
print(zero_array)

Zero Array with 5th Element Replaced:
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])

reversed_arr = arr[::-1]

print("Original Array:")
print(arr)
print("\nReversed Array:")
print(reversed_arr)

Original Array:
[1 2 0 0 4 0]

Reversed Array:
[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

rows = 5
cols = 5

array_with_border = np.zeros((rows, cols))

array_with_border[0, :] = 1
array_with_border[-1, :] = 1
array_with_border[:, 0] = 1
array_with_border[:, -1] = 1

print("2D array with 1 on border and 0 inside:")
print(array_with_border)

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

checkerboard = np.zeros((8, 8), dtype=int)

checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("8X8 Checkerboard Matrix:")
print(checkerboard)

8X8 Checkerboard Matrix:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#Problem- 3: Array Operations:

For the following arrays:

x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);

v = np.array([9,10]) and w = np.array([11,12]);

Complete all the task using numpy:

1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])

sum_array = x + y

sum_array_alt = np.add(x, y)

print("Sum of x and y:")
print(sum_array)

Sum of x and y:
[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
diff_array = x - y

diff_array_alt = np.subtract(x, y)

print("Subtraction of x and y (x - y):")
print(diff_array)

Subtraction of x and y (x - y):
[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

multiplier = 3

product_array = x * multiplier

product_array_alt = np.multiply(x, multiplier)

print("Product of x and multiplier:")
print(product_array)

Product of x and multiplier:
[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])

squared_array = np.square(x)

print("Squared elements of x:")
print(squared_array)

Squared elements of x:
[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_product_vw = np.dot(v, w)
dot_product_xv = np.dot(x, v)
dot_product_xy = np.dot(x, y)

print("Dot Product of v and w:")
print(dot_product_vw)

print("\nDot Product of x and v:")
print(dot_product_xv)

print("\nDot Product of x and y:")
print(dot_product_xy)

Dot Product of v and w:
219

Dot Product of x and v:
[29 77]

Dot Product of x and y:
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.

{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
y = np.array([[5, 6],
              [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_xy_rows = np.concatenate((x, y), axis=0)

v_col = v.reshape(-1, 1)
w_col = w.reshape(-1, 1)
concat_vw_cols = np.concatenate((v_col, w_col), axis=1)

print("Concatenate x and y along rows:\n", concat_xy_rows)
print("\nConcatenate v and w along columns:\n", concat_vw_cols)

Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]

Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
v = np.array([9, 10])

concat_xv = np.concatenate((x, v), axis=0)

print("Concatenate x and v:\n", concat_xv)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

The error occurs because x is a 2D array and v is a 1D array, and np.concatenate() requires all arrays to have the same number of dimensions except along the concatenation axis. Since their shapes don’t match, Python raises a ValueError. To fix it, reshape v to 2D (as a row or a column) before concatenating.

In [ ]:
import numpy as np

x = np.array([[1, 2],
              [3, 5]])
v = np.array([9, 10])

v_row = v.reshape(1, -1)
concat_xv_row = np.concatenate((x, v_row), axis=0)

v_col = v.reshape(-1, 1)
concat_xv_col = np.concatenate((x, v_col), axis=1)

print("x with v concatenated as a new row:\n", concat_xv_row)
print("\nx with v concatenated as a new column:\n", concat_xv_col)

x with v concatenated as a new row:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]

x with v concatenated as a new column:
 [[ 1  2  9]
 [ 3  5 10]]


#Problem- 4: Matrix Operations:

• For the following arrays:

A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);

Prove following with Numpy:

1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3, 4],
              [7, 8]])
B = np.array([[5, 3],
              [2, 1]])

A_inv = np.linalg.inv(A)
identity = np.dot(A, A_inv)

print("A * A^-1 =\n", identity)

A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB̸ = BA.

In [ ]:
AB = np.dot(A, B)
BA = np.dot(B, A)

print("A*B =\n", AB)
print("B*A =\n", BA)
print("Are AB and BA equal?", np.array_equal(AB, BA))

A*B =
 [[23 13]
 [51 29]]
B*A =
 [[36 44]
 [13 16]]
Are AB and BA equal? False


3. Prove (AB)T = BTAT.

In [ ]:
AB_T = np.dot(A, B).T
B_T_A_T = np.dot(B.T, A.T)

print("(AB)^T =\n", AB_T)
print("B^T * A^T =\n", B_T_A_T)
print("Are they equal?", np.array_equal(AB_T, B_T_A_T))

(AB)^T =
 [[23 51]
 [13 29]]
B^T * A^T =
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.

2x −3y+z =−1

x −y+2z =−3

3x +y−z =9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)

print("Solution using inverse method:", X)

Solution using inverse method: [ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.

{Explore more about ”linalg” function of Numpy}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])
X = np.linalg.inv(A) @ B

print("Solution using np.linalg.inv:", X)

Solution using np.linalg.inv: [ 2.  1. -2.]


#10.2 Experiment: How Fast is Numpy?

In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:

#1. Element-wise Addition:

• Using Python Lists, perform element-wise addition of two lists of size 1,000,000. Measure
and Print the time taken for this operation.


In [ ]:
import time
import numpy as np

list1 = range(1000000)
list2 = range(1000000)

start = time.time()
result_list = [a + b for a, b in zip(list1, list2)]
end = time.time()

print("Time using Python lists:", end - start)

Time using Python lists: 0.11266779899597168


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start = time.time()
result_array = array1 + array2
end = time.time()

print("Time using NumPy:", end - start)

Time using NumPy: 0.0038840770721435547


#2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1,000,000.
Measure and Print the time taken for this operation.

In [ ]:
import time
import numpy as np

list1 = range(1000000)
list2 = range(1000000)

start = time.time()

result_list = [a * b for a, b in zip(list1, list2)]

end = time.time()

print("Time taken using Python lists:", end - start, "seconds")

Time taken using Python lists: 0.2022261619567871 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start = time.time()

result_array = array1 * array2

end = time.time()

print("Time taken using NumPy arrays:", end - start, "seconds")

Time taken using NumPy arrays: 0.0033071041107177734 seconds


#3. Dot Product

• Using Python Lists, compute the dot product of two lists of size 1,000,000. Measure and
Print the time taken for this operation.


In [ ]:
import time
import numpy as np

list1 = range(1000000)
list2 = range(1000000)

start = time.time()

dot_product_list = sum(a * b for a, b in zip(list1, list2))

end = time.time()

print("Dot product using Python lists:", dot_product_list)
print("Time taken using Python lists:", end - start, "seconds")

Dot product using Python lists: 333332833333500000
Time taken using Python lists: 0.24273109436035156 seconds


• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for
this operation.

In [ ]:
array1 = np.arange(1000000)
array2 = np.arange(1000000)

start = time.time()

dot_product_numpy = np.dot(array1, array2)

end = time.time()

print("Dot product using NumPy:", dot_product_numpy)
print("Time taken using NumPy:", end - start, "seconds")

Dot product using NumPy: 333332833333500000
Time taken using NumPy: 0.003054380416870117 seconds


#4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import time
import random

n = 1000

A = [[random.random() for _ in range(n)] for _ in range(n)]
B = [[random.random() for _ in range(n)] for _ in range(n)]

C = [[0 for _ in range(n)] for _ in range(n)]

start = time.time()

for i in range(n):
    for j in range(n):
        for k in range(n):
            C[i][j] += A[i][k] * B[k][j]

end = time.time()

print("Time taken using Python lists:", end - start, "seconds")

Time taken using Python lists: 401.30800342559814 seconds


• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Measure and print the time taken for this operation.

In [ ]:
import numpy as np
import time

n = 1000

A_np = np.random.rand(n, n)
B_np = np.random.rand(n, n)

start = time.time()

C_np = np.dot(A_np, B_np)

end = time.time()

print("Time taken using NumPy:", end - start, "seconds")

Time taken using NumPy: 0.0572667121887207 seconds
